<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-25T21:06:15 EET" name="Default suite" finished-at="2022-11-25T21:06:28 EET" duration-ms="12750">
    <groups>
    </groups>
    <test started-at="2022-11-25T21:06:15 EET" name="Default test" finished-at="2022-11-25T21:06:28 EET" duration-ms="12750">
      <class name="package_1.DiscountCheck">
        <test-method is-config="true" signature="OpenWebsite()[pri:0, instance:package_1.DiscountCheck@3c7f66c4]" started-at="2022-11-25T21:06:15 EET" name="OpenWebsite" finished-at="2022-11-25T21:06:28 EET" duration-ms="12573" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenWebsite -->
        <test-method signature="CheckDiscount()[pri:0, instance:package_1.DiscountCheck@3c7f66c4]" started-at="2022-11-25T21:06:28 EET" name="CheckDiscount" finished-at="2022-11-25T21:06:28 EET" duration-ms="120" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [269.0] but found [369.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [269.0] but found [369.0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:701)
at org.testng.Assert.assertEquals(Assert.java:712)
at package_1.DiscountCheck.CheckDiscount(DiscountCheck.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckDiscount -->
      </class> <!-- package_1.DiscountCheck -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
